### ISSUE TITLE
Create welcome page for new members

### ISSUE THREAD

**Issue by ungoldman** [code-for-portland-archive/ideas#10]
@c4hrva has a great welcome page we can fork and edit: https://github.com/c4hrva/welcome

**Comment by ondrae** [comment]
Is this issue still something you need help with? Its getting a lot of clicks at http://www.codeforamerica.org/geeks/civicissues

Perhaps it could use some more description of how people can help. Or perhaps its old and doesn't need help anymore.

**Comment by ungoldman** [comment]
:wave:
