### ISSUE TITLE
Portland Comprehensive Plan viewing tools

### ISSUE THREAD

**Issue by ungoldman** [code-for-portland-archive/ideas#11]
From @chrissm07:

> Here's what I had in mind. We're currently getting Comp Plan comments in two forms:
> 
> 1) Generic written comments (e-mail or snailmail). These wind up as PDFs (ugh) in the City's e-File archive system, for example there are a batch here:
> 
> http://efiles.portlandoregon.gov/webdrawer.dll/webdrawer/rec/7015894/
> 
> Not very friendly at all to navigate, but almost certainly could be scraped. I'm actually reading a version that's just one big PDF for a date range (but I don't expect most people to wade through that much data in a linear fashion - my burden as a Planning Commissioner).
> 
> 2) Comments from the Map App go into their own geo-coded database.
> 
> These could probably already be scraped, but I've asked whether they can be >released as a Civic Apps data set.
> 
> What I'm wondering is whether Code for Portland could gather, OCR and index all of these into one unified set of data, and then provide tools to view it in ways that might provide greater insights (geocoding, keyword analysis, or ???). I'm sure you folks can think of more creative and useful approaches than I can.
> 
> Let me know what you think!

**Comment by fardog** [comment]
@pdxmele do you have any information on "Map App"?

**Comment by pdxmele** [comment]
Nope! But I can take a peek...

**Comment by pdxmele** [comment]
Here it is! http://www.portlandmaps.com/bps/cpmapp2/

**Comment by fardog** [comment]
Awesome. Thank you! :+1:
