### ISSUE TITLE
City of Portland tree inventory

### ISSUE THREAD

**Issue by donpdonp** [code-for-portland-archive/ideas#2]
A lot of details are missing but I was told by a city parks employee that the city is working on a total city tree inventory. I'll try to get more details as that might be interesting data.

**Comment by donpdonp** [comment]
Summary
https://www.portlandoregon.gov/parks/53181

Street Tree Data
http://www.portlandoregon.gov/parks/article/433143

**Comment by fardog** [comment]
Street Tree data on Civic Apps
http://civicapps.org/datasets/street-trees

PDX Trees iOS App
https://github.com/mattblair/pdxTrees
