### ISSUE TITLE
City of Portland Open Data Policy

### ISSUE THREAD

**Issue by chrissm07** [code-for-portland-archive/ideas#8]
I'd like to get an open data policy adopted into the City's Comprehensive Plan so it has the force of law rather than just be an aspiration (as the current policy is - it's just a City Council resolution).

Please contact me to share idea about what should be in the policy and to learn how you can add your voice to making it stronger.

Chris Smith
chris@chrissmith.us

**Comment by chrissm07** [comment]
See the issue Nate opened first!

**Comment by ungoldman** [comment]
(See #3 for reference)
